---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "glcm-matrix"
  namespace: "default"
  labels:
    app: "glcm-matrix"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "glcm-matrix"
  template:
    metadata:
      labels:
        app: "glcm-matrix"
    spec:
      containers:
      - name: "glcm-matrix-sha256-1"
        image: "gcr.io/single-planet-324918/glcm-matrix@sha256:47d349c0a73787d754840b747f6f2ff0fef28887d62f52135c2236a14e182d08"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "glcm-matrix-hpa-4fia"
  namespace: "default"
  labels:
    app: "glcm-matrix"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "glcm-matrix"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
